-- ============================================================
-- TRAÇO CIVIL — Migration V10: Schema SINAPI Composições + Custos + Mapeamento
-- ============================================================
-- Substitui a abordagem simplificada da V8 (sinapi_items) por um schema
-- normalizado que separa composição (código/descrição/unidade) do custo
-- (por UF, com/sem desoneração, por mês de referência).
--
-- Fonte de dados: planilhas oficiais CAIXA SINAPI (SINAPI_Referência_YYYY_MM.xlsx)
--   - Aba "Analítico": código (valor puro), descrição, unidade, grupo
--   - Aba "CSD" (Sem Desoneração): custo por UF
--   - Aba "CCD" (Com Desoneração): custo por UF
--
-- A tabela sinapi_items (V8) é mantida para compatibilidade retroativa
-- mas não será mais populada — o novo fluxo usa estas 3 tabelas.
-- ============================================================

-- 1. Composições SINAPI (catálogo mestre)
CREATE TABLE IF NOT EXISTS sinapi_composicoes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(50)  NOT NULL UNIQUE,
    descricao       TEXT         NOT NULL,
    unidade         VARCHAR(20)  NOT NULL,
    grupo           VARCHAR(200),
    mes_referencia  VARCHAR(7)   NOT NULL,  -- formato 'YYYY-MM'
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sinapi_comp_codigo ON sinapi_composicoes(codigo);
CREATE INDEX IF NOT EXISTS idx_sinapi_comp_grupo ON sinapi_composicoes(grupo);
CREATE INDEX IF NOT EXISTS idx_sinapi_comp_mes ON sinapi_composicoes(mes_referencia);

COMMENT ON TABLE sinapi_composicoes IS 'Catálogo mestre de composições SINAPI (CAIXA). Código vem da aba Analítico (valor puro, não hyperlink).';
COMMENT ON COLUMN sinapi_composicoes.codigo IS 'Código oficial SINAPI (ex: 103366). Fonte: aba Analítico, coluna Código.';
COMMENT ON COLUMN sinapi_composicoes.unidade IS 'Unidade de medida: m2, m3, kg, un, vb, etc.';
COMMENT ON COLUMN sinapi_composicoes.grupo IS 'Grupo/classe da composição (ex: ESTRUTURAS, INSTALAÇÕES).';
COMMENT ON COLUMN sinapi_composicoes.mes_referencia IS 'Mês de referência dos preços no formato YYYY-MM (ex: 2026-07).';

-- 2. Custos por UF e tipo de desoneração
CREATE TABLE IF NOT EXISTS sinapi_composicao_custos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composicao_id   BIGINT       NOT NULL REFERENCES sinapi_composicoes(id) ON DELETE CASCADE,
    uf              CHAR(2)      NOT NULL,  -- SP, RJ, MG, etc.
    desoneracao     BOOLEAN      NOT NULL DEFAULT FALSE,  -- false=CSD, true=CCD
    custo           NUMERIC(12,2) NOT NULL DEFAULT 0,
    mes_referencia  VARCHAR(7)   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sinapi_custo UNIQUE (composicao_id, uf, desoneracao, mes_referencia)
);

CREATE INDEX IF NOT EXISTS idx_sinapi_custo_comp ON sinapi_composicao_custos(composicao_id);
CREATE INDEX IF NOT EXISTS idx_sinapi_custo_uf ON sinapi_composicao_custos(uf);
CREATE INDEX IF NOT EXISTS idx_sinapi_custo_deson ON sinapi_composicao_custos(desoneracao);
CREATE INDEX IF NOT EXISTS idx_sinapi_custo_mes ON sinapi_composicao_custos(mes_referencia);

COMMENT ON TABLE sinapi_composicao_custos IS 'Custos unitários por UF e tipo de desoneração. Índice único evita duplicação em reimportações.';
COMMENT ON COLUMN sinapi_composicao_custos.uf IS 'Unidade Federativa (2 chars): SP, RJ, MG, RS, etc.';
COMMENT ON COLUMN sinapi_composicao_custos.desoneracao IS 'false = CSD (Sem Desoneração), true = CCD (Com Desoneração).';
COMMENT ON COLUMN sinapi_composicao_custos.custo IS 'Preço unitário em R$ (NUMERIC para precisão financeira).';

-- 3. Mapeamento elemento IA → composição SINAPI
CREATE TABLE IF NOT EXISTS sinapi_elemento_mapeamento (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elemento            VARCHAR(50)  NOT NULL UNIQUE,  -- 'concreto', 'aco', 'alvenaria', 'forma'
    composicao_codigo   VARCHAR(50)  NOT NULL,         -- código SINAPI correspondente
    fator_conversao     NUMERIC(10,4) NOT NULL DEFAULT 1,  -- ex: 1000 para ton→kg
    descricao           TEXT,                           -- nota explicativa
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sinapi_map_elem ON sinapi_elemento_mapeamento(elemento);
CREATE INDEX IF NOT EXISTS idx_sinapi_map_cod ON sinapi_elemento_mapeamento(composicao_codigo);

COMMENT ON TABLE sinapi_elemento_mapeamento IS 'Mapeamento dos elementos detectados pela IA para códigos SINAPI. fator_conversao ajusta unidades (ex: aço ton→kg = 1000).';
COMMENT ON COLUMN sinapi_elemento_mapeamento.elemento IS 'Nome do elemento como retornado pela IA: concreto, aco, alvenaria, forma.';
COMMENT ON COLUMN sinapi_elemento_mapeamento.fator_conversao IS 'Multiplicador para converter a unidade da IA na unidade SINAPI. Ex: IA retorna aço em toneladas, SINAPI em kg → fator=1000.';

-- 4. Seed: mapeamento dos 4 elementos que a IA já detecta
INSERT INTO sinapi_elemento_mapeamento (elemento, composicao_codigo, fator_conversao, descricao) VALUES
    ('alvenaria', '103366', 1,    'Alvenaria de vedação — unidade M2, IA retorna em M2 (sem conversão)'),
    ('aco',       '92919',  1000, 'Aço CA-50 — unidade KG, IA retorna em toneladas (×1000)'),
    ('concreto',  '103670', 1,    'Concreto estrutural — unidade M3, IA retorna em M3 (aproximação genérica)'),
    ('forma',     '92415',  1,    'Fôrma para concreto — unidade M2, IA retorna em M2 (aproximação genérica)')
ON CONFLICT (elemento) DO NOTHING;