-- ============================================================
-- TRAÇO CIVIL — Migration V1: Tabela de Usuários (Segurança)
-- ============================================================
-- Esta tabela armazena os usuários do sistema com senhas hasheadas (BCrypt).
-- Campos de segurança:
--   - password: armazenado como hash BCrypt (nunca em texto plano)
--   - role: controle de acesso baseado em roles (engenheiro, arquiteto, admin)
--   - created_at: timestamp de criação para auditoria
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(50)  NOT NULL DEFAULT 'engenheiro',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índice para busca rápida por email (login)
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Comentário de segurança: senhas devem ser hasheadas com BCrypt (cost >= 10)
COMMENT ON COLUMN users.password IS 'Hash BCrypt da senha - nunca armazenar em texto plano';
COMMENT ON COLUMN users.role IS 'Role de acesso: engenheiro, arquiteto, admin';