-- ============================================================
-- TRAÇO CIVIL — Migration V2: Tabela de Projetos
-- ============================================================
-- Projetos de engenharia civil vinculados a um usuário.
-- Campos:
--   - type: residencial | comercial | industrial
--   - status: ativo | concluido | rascunho
-- ============================================================

CREATE TABLE IF NOT EXISTS projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(50)  NOT NULL DEFAULT 'residencial',
    status      VARCHAR(50)  NOT NULL DEFAULT 'rascunho',
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);

COMMENT ON COLUMN projects.type IS 'Tipo de obra: residencial, comercial, industrial';
COMMENT ON COLUMN projects.status IS 'Status do projeto: ativo, concluido, rascunho';