-- ============================================================
-- TRAÇO CIVIL — Migration V3: Tabela de Plantas (Domínio Civil)
-- ============================================================
-- Armazena metadados das plantas baixadas/uploadadas (PDF, DWG, PNG, JPG).
-- O arquivo binário fica em storagePath (sistema de arquivos ou object storage).
-- Campos de análise IA (preenchidos após processamento):
--   - area: área total estimada em m²
--   - rooms: quantidade de cômodos detectados
--   - status: processando | concluida | erro
-- ============================================================

CREATE TABLE IF NOT EXISTS plantas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    format        VARCHAR(10)  NOT NULL,
    size_bytes    BIGINT       NOT NULL DEFAULT 0,
    storage_path  VARCHAR(500),
    status        VARCHAR(50)  NOT NULL DEFAULT 'processando',
    area          DOUBLE PRECISION,
    rooms         INTEGER,
    project_id    BIGINT       REFERENCES projects(id) ON DELETE SET NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_plantas_project ON plantas(project_id);
CREATE INDEX IF NOT EXISTS idx_plantas_status ON plantas(status);

COMMENT ON COLUMN plantas.format IS 'Formato do arquivo: PDF, DWG, PNG, JPG';
COMMENT ON COLUMN plantas.status IS 'Status de processamento: processando, concluida, erro';
COMMENT ON COLUMN plantas.storage_path IS 'Caminho relativo ao diretório de uploads - nunca expor publicamente sem token assinado';