-- ============================================================
-- TRAÇO CIVIL — Migration V4: Tabela de Análises (IA + Orçamento)
-- ============================================================
-- Resultados do processamento de IA sobre uma planta: quantitativos,
-- elementos detectados, caixas delimitadoras e custo estimado (SINAPI).
-- Campos JSON armazenam arrays serializados (elementsJson, quantitiesJson, boxesJson).
-- Segurança: estimatedCost e dados sensíveis são de leitura restrita por projeto/usuário.
-- ============================================================

CREATE TABLE IF NOT EXISTS analyses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(50)  NOT NULL UNIQUE,
    project_id        BIGINT       REFERENCES projects(id) ON DELETE CASCADE,
    planta_id         BIGINT       UNIQUE REFERENCES plantas(id) ON DELETE SET NULL,
    status            VARCHAR(50)  NOT NULL DEFAULT 'processando',
    duration_seconds  INTEGER,
    confidence        INTEGER,
    area              DOUBLE PRECISION,
    rooms             INTEGER,
    estimated_cost    DOUBLE PRECISION,
    elements_json     TEXT,
    quantities_json   TEXT,
    boxes_json        TEXT,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analyses_project ON analyses(project_id);
CREATE INDEX IF NOT EXISTS idx_analyses_planta ON analyses(planta_id);
CREATE INDEX IF NOT EXISTS idx_analyses_status ON analyses(status);
CREATE INDEX IF NOT EXISTS idx_analyses_code ON analyses(code);

COMMENT ON COLUMN analyses.code IS 'Código único da análise no formato ANL-XXXX';
COMMENT ON COLUMN analyses.status IS 'Status: processando, concluida, revisada, erro';
COMMENT ON COLUMN analyses.elements_json IS 'JSON: elementos estruturais detectados pela IA';
COMMENT ON COLUMN analyses.quantities_json IS 'JSON: quantitativos de materiais (base SINAPI)';
COMMENT ON COLUMN analyses.boxes_json IS 'JSON: bounding boxes dos cômodos/elementos na planta';
COMMENT ON COLUMN analyses.estimated_cost IS 'Custo estimado em R$ baseado em quantitativos + SINAPI';