-- ============================================================
-- TRAÇO CIVIL — Migration V5: Tabela de Auditoria (Cibersegurança)
-- ============================================================
-- Log imutável de eventos de segurança e ações críticas do sistema.
-- Usado para:
--   - Rastrear tentativas de login (sucesso/falha)
--   - Auditar acesso a dados sensíveis (plantas, orçamentos)
--   - Detectar padrões suspeitos (múltiplas falhas, acessos fora de horário)
--   - Compliance e forense digital
-- Segurança: esta tabela é append-only; nenhum UPDATE/DELETE deve ser permitido
-- em produção (considere triggers ou políticas de banco para reforçar).
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(100) NOT NULL,
    severity      VARCHAR(20)  NOT NULL DEFAULT 'INFO',
    user_id       BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    user_email    VARCHAR(255),
    ip_address    VARCHAR(64),
    user_agent    VARCHAR(500),
    resource      VARCHAR(255),
    action        VARCHAR(100),
    details       TEXT,
    success       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_event ON audit_log(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_severity ON audit_log(severity);
CREATE INDEX IF NOT EXISTS idx_audit_success ON audit_log(success);

COMMENT ON COLUMN audit_log.event_type IS 'Tipo de evento: LOGIN_SUCCESS, LOGIN_FAILURE, PLANTA_UPLOADED, ANALYSIS_COMPLETED, DATA_ACCESS, etc.';
COMMENT ON COLUMN audit_log.severity IS 'Severidade: INFO, WARN, ERROR, CRITICAL';
COMMENT ON COLUMN audit_log.ip_address IS 'Endereço IP do cliente (respeitar LGPD - considerar anonimização parcial)';
COMMENT ON COLUMN audit_log.details IS 'Detalhes adicionais em JSON ou texto livre (nunca armazenar senhas ou tokens)';
COMMENT ON COLUMN audit_log.success IS 'Indica se a ação foi bem-sucedida ou falhou';