-- ============================================================
-- TRAÇO CIVIL — Migration V6: Tabela de Tentativas de Login (Segurança)
-- ============================================================
-- Rastreia tentativas de autenticação para implementar:
--   - Bloqueio temporário após N falhas consecutivas (brute-force protection)
--   - Rate limiting por IP e por email
--   - Detecção de credential stuffing (múltiplos emails do mesmo IP)
-- Segurança: dados de IP devem ser anonimizados parcialmente em conformidade LGPD.
-- Retenção: registros antigos (> 90 dias) podem ser arquivados/purgados via job.
-- ============================================================

CREATE TABLE IF NOT EXISTS login_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    ip_address    VARCHAR(64),
    user_agent    VARCHAR(500),
    success       BOOLEAN      NOT NULL DEFAULT FALSE,
    failure_reason VARCHAR(100),
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_email ON login_attempts(email);
CREATE INDEX IF NOT EXISTS idx_login_ip ON login_attempts(ip_address);
CREATE INDEX IF NOT EXISTS idx_login_created ON login_attempts(created_at);
CREATE INDEX IF NOT EXISTS idx_login_success ON login_attempts(success);

COMMENT ON COLUMN login_attempts.email IS 'Email tentado (mesmo que não exista no sistema - para detectar enumeração)';
COMMENT ON COLUMN login_attempts.ip_address IS 'IP do cliente - considerar armazenar apenas /24 ou hash para LGPD';
COMMENT ON COLUMN login_attempts.failure_reason IS 'Motivo da falha: INVALID_CREDENTIALS, ACCOUNT_LOCKED, RATE_LIMITED, etc.';