-- ============================================================
-- TRAÇO CIVIL — Migration V7: Métricas de Cibersegurança
-- ============================================================
-- Tabela para armazenar métricas agregadas de segurança, usadas em dashboards
-- e alertas proativos. Atualizada por jobs periódicos ou triggers.
-- Métricas incluem:
--   - Taxa de falhas de login por período
--   - Tentativas de acesso não autorizado
--   - Volume de uploads suspeitos
--   - Tempo médio de resposta a incidentes
-- Segurança: dados agregados apenas - nunca armazenar PII diretamente aqui.
-- ============================================================

CREATE TABLE IF NOT EXISTS security_metrics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name     VARCHAR(100) NOT NULL,
    metric_value    DOUBLE PRECISION NOT NULL,
    period_start    TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end      TIMESTAMP WITH TIME ZONE NOT NULL,
    details         TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sec_metrics_name ON security_metrics(metric_name);
CREATE INDEX IF NOT EXISTS idx_sec_metrics_period ON security_metrics(period_start, period_end);

COMMENT ON COLUMN security_metrics.metric_name IS 'Nome da métrica: LOGIN_FAILURE_RATE, UNAUTHORIZED_ACCESS_ATTEMPTS, SUSPICIOUS_UPLOADS, etc.';
COMMENT ON COLUMN security_metrics.metric_value IS 'Valor numérico da métrica no período';
COMMENT ON COLUMN security_metrics.details IS 'Detalhes adicionais em JSON (breakdown por categoria, top IPs, etc.)';