-- ============================================================
-- TRAÇO CIVIL — Migration V8: Tabela de Itens SINAPI (Orçamento)
-- ============================================================
-- Catálogo de itens da tabela SINAPI (Sistema Nacional de Pesquisa de
-- Custos e Índices da Construção Civil) da CAIXA. Usado para precificação
-- automática dos quantitativos extraídos pela IA.
-- Campos:
--   - code: código SINAPI (ex: 87263)
--   - description: descrição do item/serviço
--   - unit: unidade de medida (m², m³, kg, un, vb, etc.)
--   - price: preço unitário médio (R$) - atualizado periodicamente
--   - category: categoria (materiais, mão de obra, equipamentos, serviços)
-- Segurança: dados públicos (CAIXA), mas acesso restrito por role se necessário.
-- ============================================================

CREATE TABLE IF NOT EXISTS sinapi_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    description   TEXT         NOT NULL,
    unit          VARCHAR(20)  NOT NULL,
    price         DOUBLE PRECISION NOT NULL DEFAULT 0,
    category      VARCHAR(100),
    region        VARCHAR(50)  DEFAULT 'NACIONAL',
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sinapi_code ON sinapi_items(code);
CREATE INDEX IF NOT EXISTS idx_sinapi_category ON sinapi_items(category);
CREATE INDEX IF NOT EXISTS idx_sinapi_region ON sinapi_items(region);

COMMENT ON COLUMN sinapi_items.code IS 'Código oficial SINAPI (CAIXA)';
COMMENT ON COLUMN sinapi_items.price IS 'Preço unitário médio em R$ - atualizar mensalmente conforme divulgação CAIXA';
COMMENT ON COLUMN sinapi_items.region IS 'Região de aplicação: NACIONAL ou UF específica (SP, RJ, MG, etc.)';